### PR TITLE
fix the example in man page.

### LINKED ISSUE #311: Default WipBranchQualifierSeparator is wrong in `README.md`
In the README we tell about the `--branch` parameter for mob start and mob reset. There we explain, the following `[--branch|-b <branch-postfix>]       Set wip branch to 'mob/<base-branch>/<branch-postfix>'` The `/` between `<basebranch>` and `<branch-postfix>` is the configuration value if WipBranchQualifierSeparator. But the default value for this is not `/` it is `-`. So the example in the `README.md` is wrong.

### PR DESCRIPTION
**Pull request by rustiever**
Fixes #311

### CODE REVIEW

**Comment by hollesse** [comment]
looks good to me. Thank you for your contribution @rustiever

**Comment by rustiever** [comment]
Thanks for merging the code, is there any other good first issues deals with code i can work with??

**Comment by hollesse** [comment]
If you are developing on windows you could have a look at #322. At the moment I don't have anything else as a good first issue. Even there I'm not sure if it is that simple for a beginner.

**Comment by rustiever** [comment]
Unfortunately I don't have windows system, i work with Linux. If you have any intermediate level tasks, let me give a try

**Comment by hollesse** [comment]
You could also try #290 this need changes in the mob timer project which is developed in Java with spring boot and here to connect with the web timer. This could be something you could try.

**Pull request merged**
