### PR TITLE
Update scoop install instructions

### PR DESCRIPTION
**Pull request by WtfJoke**
mob was just added to the scoop main bucket https://github.com/ScoopInstaller/Main/pull/1743 🎉 

- The scoop manifest in this repo is no longer needed, so I removed it
- I updated the readme and moved the scoop part up (as its less complicated now and the instructions can kept short - the first time I havent noticed that its possible to install it that way as its quite hidden back down the readme, not where you would except)

Hope youre fine with the changes. Hit me up if you think the PR can improved in any way.

### CODE REVIEW

**Comment by simonharrer** [comment]
Awesome!

If there is a new release of mob, will the scoop install command automatically install the newer version or is some manual work necessary to update the main scoop repo?

**Comment by WtfJoke** [comment]
Its my first contribution to the scoop main bucket, but according to the [Scoop Wiki](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate#testing-and-running-autoupdate) no manual work is required when you make a new release of mob:

> Manifests in some known buckets are autoupdated by ScoopInstaller/Excavator, so if you want some apps being autoupdated, migrate them to one of these buckets or run an instance of the excavator yourself.
> 
>     main: Update per hour
>     extras: Update per hour
>     versions: Update per day
>     java: Update per day
>     php: Update per day
>     games: Update per day


This is possible because I included autoupdate instructions in the scoop manifest.
```json
"checkver": {
    "github": "https://github.com/remotemobprogramming/mob"
},
"autoupdate": {
    "url": "https://github.com/remotemobprogramming/mob/releases/download/v$version/mob_v$version_windows_amd64.tar.gz",
    "hash": {
        "url": "$baseurl/mob_v$version_windows_amd64_checksum.txt"
    }
}
```

**Disclaimer**: As long as you dont change the filename pattern of the released artifacts, you're all set :D


You can verify it, after you publish a new release

**Comment by simonharrer** [comment]
Great! Will try it out soon. :-)

**Comment by simonharrer** [comment]
Thanks for all your help!

**Comment by WtfJoke** [comment]
No worries :) Thank you for your fast responses!

**Comment by simonharrer** [comment]
Btw. I renamed the word Swift with the word smooth. Might be necessary to change this in the meta info of the scoop json file as well.

**Comment by WtfJoke** [comment]
Its not necessary as its only meta information and could be omitted. 

If its important for you we can change it. The PR there took a couple of days to merge, though.

**Comment by simonharrer** [comment]
If you have time it would be great. But it’s not a problem if you don’t find the time.

**Comment by WtfJoke** [comment]
https://github.com/ScoopInstaller/Main/pull/1772

**Pull request merged**
