### PR TITLE
Fixes a bug where next() fails when the WipBranchQualifier contains the WipBranchQualifierSeparator

### PR DESCRIPTION
**Pull request by gregorriegler**

### CODE REVIEW

**Comment by simonharrer** [comment]
Thanks for the help!

**Comment by simonharrer** [comment]
@gregorriegler a little bit strange, the tests fail on master after the merge. No idea why at the moment, because I thought Github Actions said tests are green....

**Comment by gregorriegler** [comment]
Yes, all tests were green. Was there a merge conflict?

Simon Harrer <notifications@github.com> schrieb am Sa., 30. Jän. 2021,
13:59:

**Comment by gregorriegler** [comment]
Could as well be a flaky test depending on test order because of the state of the configuration global.

**Comment by simonharrer** [comment]
No merge conflict. Test order could be it. Will have a look.

**Comment by simonharrer** [comment]
Cannot reproduce green tests when checking out this PR alone.

**Comment by simonharrer** [comment]
Does `go test` really work in your https://github.com/gregorriegler/mob master branch?

**Pull request merged**
