### PR TITLE
Amadeus as user

### PR DESCRIPTION
**Pull request by alonsomoya**
[Amadeus](https://amadeus.com/) is a proud user of mob in our remote teams part of our cloud migration program

### CODE REVIEW

**Comment by hollesse** [comment]
@alonsomoya may I ask why did you close this PR? Should we not name Amadeus in the list of happy users?

**Comment by alonsomoya** [comment]
hi @hollesse just put it on hold pending clarification with my company OSPO representatives. Still happy users and ready to merge ✌

**Comment by hollesse** [comment]
@alonsomoya ah okay I understand. I will then wait with merging until you tell me it is fine for your representatives.

**Comment by simonharrer** [comment]
Thanks for adding your company to the list of proud users. :-)

**Pull request merged**
