### PR TITLE
Truncate list of last commits if it is longer than 5 entries

### PR DESCRIPTION
**Pull request by Morl99**
See https://twitter.com/Morl99/status/1365360716610478080 for the discussion about the feature

I am very new to go and would happily take any comments about how this code could be simpler, if possible. 
I decided to write a test for the "happy" case, where the new code actually makes any difference, and decided that for everything else, the existing tests are good enough.

@simonharrer do you think that this should be configurable behaviour? Can you think of a use case, where mob should consistently print the whole list, or more than 5 entries? 

PS: I was unable to execute the commans that are documented in the "How to contribute section", as Go always complained about a missing module. I readded the module file that you created yesterday and it worked like a charm. I am using go 1.16, not sure if this has anything to do with it. Just wanted to let you know, I did not commit go.mod because I do not want to mess with your project setup.

### CODE REVIEW

**Comment by Morl99** [comment]
Just came across #134 which explains it all, so just ignore my comment. I read go >= 1.15 in the docs and thought I was good to go with 1.16. Might be safer to document the exact Version that is supported.

**Comment by simonharrer** [comment]
can you double check that the mob status command doesn’t add a empty line if there are no commits? Maybe use a test for that. Otherwise it looks fine for me.

**Comment by simonharrer** [comment]
can you add an entry to the changelog.md targeting 1.4.0?

**Comment by Morl99** [comment]
> can you double check that the mob status command doesn’t add a empty line if there are no commits? Maybe use a test for that. Otherwise it looks fine for me.

That would have been the case before as well, right? You mean the call to say with a potentially empty output?  I can take a look at it, once I come back to my computer (done for the day ;))

**Comment by Morl99** [comment]
I added a test that shows, that no empty line is added, and I included a changelog entry.
Does that work for you?

**Comment by simonharrer** [comment]
LGTM Thanks for your contribution!

**Pull request merged**
