### PR TITLE
#406 - removed cancelation of mob timers

### LINKED ISSUE #406: Remove cancellation of the local mob timer when doing mob done or mob next
We should remove this feature for the following reasons:

- If you switch from one codebase to another the timer gets stopped and a new timer will start. This could lead to longer rotation times
- the way we stop the timer is just searching for the right process and killing it. This is a behavior which is suspicious for the most virus detection applications and could be one cause why mob is listed for some virus detection tools in windows. (see #357)

### PR DESCRIPTION
**Pull request by hollesse**
This MR closes #406

### CODE REVIEW

**Review by gregorriegler — COMMENTED** [review]
this is definitely something we should try quickly to get rid of the malware detection.
Since its behaving differently with the timer now, we should at least change the minor version, no?

**Comment by gregorriegler** [comment]
changed version. feel free to merge

**Comment by hollesse** [comment]
I agree it should be a minor version change. But then the Version should be 4.5.0 correct?

**Comment by gregorriegler** [comment]
of course 😃

**Pull request merged**
