### PR TITLE
added reset warning and delete-remote-wip-branch parameter

### PR DESCRIPTION
**Pull request by hollesse**
adds functionality of #298

### CODE REVIEW

**Review by gregorriegler — COMMENTED** [review]
LGTM, just need docs and changelog

**Comment by simonharrer** [comment]
Be aware that this is a breaking change.

**Comment by hollesse** [comment]
I also see there is another parameter for reset. I did not test it with this parameter. I will add a test for this.

**Review by gregorriegler — APPROVED** [review]

**Comment by simonharrer** [comment]
If you increase the major version you have to increase the package as well. @hollesse

**Comment by hollesse** [comment]
I wasn't even finished with adding everything to the read me and help and also the missing test :D I will add it, but we should not release until that is done @gregorriegler @simonharrer

**Pull request merged**
