### PR TITLE
Test behaviour on pre existing commits

### PR DESCRIPTION
**Pull request by gregorriegler**
Found and addressed a bug where when one of the mobbers has had an unpushed commit thus other mobbers were behind on the base branch. They ran into a problem when they would do `mob done --squash-wip`

### CODE REVIEW

**Comment by simonharrer** [comment]
Which of the new tests would fail with the old behavior?

**Comment by simonharrer** [comment]
Fine for me. Can you add a changelog, please?

**Comment by gregorriegler** [comment]
The more I think about it the more I dislike it.
The wip branch shouldn't diverge from the main branch ever. ( I cannot outrule a conflict )
When it diverges, mobbers should be warned and guided to resolve it instead.

**Comment by gregorriegler** [comment]
@simonharrer what should happen in your opinion if the base branch diverges from the mob branch?

**Comment by simonharrer** [comment]
With squash, it’s not that large of an issue as you normally don’t have conflicts - at least in my experience. And if you do, you have to fix them manually with the staged changes until you make the final commit.

With squash-wip it should behave the same.

With no-squash, it’s more of a problem as it creates a merge commit. But also ok.

**Comment by simonharrer** [comment]
We could add an info to the user that the mob branch diverged from when it was created.

**Comment by gregorriegler** [comment]
I prefer that. If users get the info that it diverges, they at least have the choice to fix it on the wip-branch rather than on the main-branch

**Comment by gregorriegler** [comment]
Tried to rebase my branch onto latest main with IntelliJ which failed and I didn't notice it. 
It had put my commits before all other commits on my branch (really strange). 
So I just undid this and force pushed my branch to do it properly using the CLI.

Added the changelog.

I did some testing. 
The behavior on a non-auto-mergeagle diverging change is just the same as with a simple `mob done`.
This is a behavior that is already well handled. A bit late maybe (on `done`), but its handled.

So I would keep it this way. 
If we want to improve on the behavior on a non-auto-mergeagle conflict later (e.g. detect it earlier) we should do this on a separate branch IMO.

**Comment by gregorriegler** [comment]
@simonharrer resolved the conflict

**Pull request merged**
